#!/bin/bash

echo "The first column indicates the number of inotify fds (not the number of watches though) and the second shows the PID of that process [sources: 1, 2]."
# SOURCE: https://unix.stackexchange.com/questions/13751/kernel-inotify-watch-limit-reached
find /proc/*/fd -lname anon_inode:inotify | cut -d/ -f3 | xargs -I '{}' -- ps --no-headers -o '%p %U %c' -p '{}' | uniq -c | sort -nr
