#!/bin/bash

apt-get update
apt-get upgrade -y
# apt-get install libjemalloc1 libjemalloc-dev -y
apt-get install libsystemd-dev -y
apt-get install libsystemd0 cmake -y

apt-get remove -y libjemalloc-dev libjemalloc1

apt-get install -y libgtest-dev doxygen graphviz
apt-get install cmake libgtest-dev -y

export JEMALLOC_VERSION=4.5.0
export FLUENTD_VERSION1.0.4

wget -O /tmp/jemalloc-$JEMALLOC_VERSION.tar.bz2 https://github.com/jemalloc/jemalloc/releases/download/$JEMALLOC_VERSION/jemalloc-$JEMALLOC_VERSION.tar.bz2 && \
cd /tmp && tar -xjf jemalloc-$JEMALLOC_VERSION.tar.bz2 && cd jemalloc-$JEMALLOC_VERSION/ && \
./configure && make && \
mv lib/libjemalloc.so.2 /usr/lib

ldconfig

export LD_PRELOAD="/usr/lib/libjemalloc.so.2"

# https://github.com/AppImage/AppImageKit/issues/571
cd /usr/src/gtest
cmake CMakeLists.txt
make
# copy or symlink libgtest.a and libgtest_main.a to your /usr/lib folder
cp *.a /usr/lib


curl -L 'https://fluentbit.io/releases/1.0/fluent-bit-1.0.4.tar.gz' > /usr/local/src/fluent-bit-1.0.4.tar.gz
pushd /usr/local/src
tar -xvf fluent-bit-1.0.4.tar.gz
cd /usr/local/src
cd fluent-bit-1.0.4
mkdir build
cd build
cmake ../ -DFLB_ALL=yes -DFLB_JEMALLOC=yes
make
make install

echo "-----------------------------------------------------"
echo "[run] cat /lib/systemd/system/fluent-bit.service"
echo "-----------------------------------------------------"
cat /lib/systemd/system/fluent-bit.service
echo "-----------------------------------------------------"
echo ""

mkdir -p /etc/systemd/system/fluent-bit.service.d
cat <<EOF >/etc/systemd/system/fluent-bit.service.d/perf.conf
[Service]
Restart=on-failure
RestartSec=20
TimeoutStartSec=0
EnvironmentFile=/etc/environment
Environment="LD_PRELOAD=/usr/lib/libjemalloc.so.2"

LimitMEMLOCK=infinity
# LimitNOFILE=524288
LimitNOFILE=20288

EOF

echo "-----------------------------------------------------"
echo "[run] cat /etc/systemd/system/fluent-bit.service.d/perf.conf"
echo "-----------------------------------------------------"
cat /etc/systemd/system/fluent-bit.service.d/perf.conf
echo "-----------------------------------------------------"
echo ""

mkdir -p /etc/fluent-bit/
cp -fv /usr/local/etc/fluent-bit/parsers.conf /etc/fluent-bit/

cat <<EOF >/etc/fluent-bit/fluent-bit.conf
[SERVICE]
    Flush        1
    Log_Level    info
    Parsers_File /etc/fluent-bit/parsers.conf

[INPUT]
    Name         syslog
    Path         /tmp/in_syslog
    Chunk_Size   32
    Buffer_Size  64

[OUTPUT]
    Name   stdout
    Match  *

EOF

systemctl daemon-reload
systemctl fluent-bit restart
systemctl fluent-bit enable

# fluent-bit -R /etc/fluent-bit/parsers.conf -i syslog -p path=/tmp/in_syslog -o stdout
# logger -u /tmp/in_syslog my_ident my_message

# cat <<EOF >/etc/fluent-bit/fluent-bit.conf
# [SERVICE]
#     # Flush
#     # =====
#     # Set an interval of seconds before to flush records to a destination
#     Flush        5

#     # Daemon
#     # ======
#     # Instruct Fluent Bit to run in foreground or background mode.
#     Daemon       Off

#     # Log_Level
#     # =========
#     # Set the verbosity level of the service, values can be:
#     #
#     # - error
#     # - warning
#     # - info
#     # - debug
#     # - trace
#     #
#     # By default 'info' is set, that means it includes 'error' and 'warning'.
#     Log_Level    info

#     # Parsers_File
#     # ============
#     # Specify an optional 'Parsers' configuration file
#     Parsers_File /etc/fluent-bit/parsers.conf
#     Plugins_File plugins.conf

#     # HTTP Server
#     # ===========
#     # Enable/Disable the built-in HTTP Server for metrics
#     HTTP_Server  Off
#     HTTP_Listen  0.0.0.0
#     HTTP_Port    2020

# [INPUT]
#     Name cpu
#     Tag  cpu.local
#     # Interval Sec
#     # ====
#     # Read interval (sec) Default: 1
#     Interval_Sec 1

# [OUTPUT]
#     Name  stdout
#     Match *
#
# EOF
