#!/bin/bash

echo "* soft     nproc          90000" > /etc/security/limits.d/perf.conf
echo "* hard     nproc          90000" >> /etc/security/limits.d/perf.conf
echo "* soft     nofile         90000" >> /etc/security/limits.d/perf.conf
echo "* hard     nofile         90000"  >> /etc/security/limits.d/perf.conf
echo "root soft     nproc          90000" >> /etc/security/limits.d/perf.conf
echo "root hard     nproc          90000" >> /etc/security/limits.d/perf.conf
echo "root soft     nofile         90000" >> /etc/security/limits.d/perf.conf
echo "root hard     nofile         90000" >> /etc/security/limits.d/perf.conf
sed -i '/pam_limits.so/d' /etc/pam.d/sshd
echo "session    required   pam_limits.so" >> /etc/pam.d/sshd
sed -i '/pam_limits.so/d' /etc/pam.d/su
echo "session    required   pam_limits.so" >> /etc/pam.d/su
sed -i '/session required pam_limits.so/d' /etc/pam.d/common-session
echo "session required pam_limits.so" >> /etc/pam.d/common-session
sed -i '/session required pam_limits.so/d' /etc/pam.d/common-session-noninteractive
echo "session required pam_limits.so" >> /etc/pam.d/common-session-noninteractive
