#!/bin/bash

source /usr/local/bin/color-echo-helper

# SOURCE: https://wiki.ubuntu.com/Debug%20Symbol%20Packages

cat <<EOF >/etc/apt/sources.list.d/ddebs.list
deb http://ddebs.ubuntu.com bionic main restricted
deb http://ddebs.ubuntu.com bionic multiverse
deb http://ddebs.ubuntu.com bionic universe
deb http://ddebs.ubuntu.com bionic-updates main restricted
deb http://ddebs.ubuntu.com bionic-updates multiverse
deb http://ddebs.ubuntu.com bionic-updates universe
EOF

cat /etc/apt/sources.list.d/ddebs.list

sudo apt install ubuntu-dbgsym-keyring -y

sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys F2EDC64DC5AEE1F6B9C621F0C8CAB6595FDFF622

apt-get update


#  sudo bash ./list-symbols-packages-v2.sh -p $(pidof yelp)

echo
cecho ' [example] list-symbols-packages-v2.sh -p $(pidof yelp) 2>/dev/null| xargs -d $"\n" sudo apt-get install ' $GREEN
echo
