#!/bin/bash

curl -L 'https://raw.githubusercontent.com/johanhaleby/kubetail/master/kubetail' > /usr/local/bin/kubetail

sudo chmod +x /usr/local/bin/kubetail

curl -L 'https://raw.githubusercontent.com/johanhaleby/kubetail/master/completion/kubetail.bash' | sudo tee /etc/bash_completion.d/kubetail.bash

sudo chmod +x /etc/bash_completion.d/kubetail.bash
