#!/bin/bash

source /usr/local/bin/color-echo-helper

# SOURCE: https://github.com/mesosphere/kubernetes-mesos/issues/151

# SOURCE: http://www.brendangregg.com/blog/2017-03-16/perf-sched.html

# perf record

cecho " [run] perf record for 15 seconds " $GREEN
cecho " [cmd] perf sched record -- sleep 15" $BLUE
perf sched record -- sleep 15
echo

cecho " [run] perf script header " $GREEN
cecho " [cmd] perf script --header" $BLUE
perf script --header
echo

cecho " [run] perf sched latency will summarize scheduler latencies by task, including average and maximum delay " $GREEN
cecho " [cmd] perf sched latency" $BLUE
perf sched latency
echo

cecho " [run] perf report --stdio --sort=comm,dso " $GREEN
cecho " [cmd] perf report --stdio --sort=comm,dso" $BLUE
perf report --stdio --sort=comm,dso
echo

# perf report --stdio --dsos=libmesos-0.21.0.so

cecho " [run] perf report " $GREEN
cecho " [cmd] perf report" $BLUE
perf report
echo
